/** Common ISO 4217 choices; any other valid code can still be set programmatically if needed. */
export const CURRENCY_OPTIONS: { code: string; label: string }[] = [
  { code: 'USD', label: 'US dollar' },
  { code: 'EUR', label: 'Euro' },
  { code: 'GBP', label: 'British pound' },
  { code: 'CAD', label: 'Canadian dollar' },
  { code: 'AUD', label: 'Australian dollar' },
  { code: 'NZD', label: 'New Zealand dollar' },
  { code: 'CHF', label: 'Swiss franc' },
  { code: 'JPY', label: 'Japanese yen' },
  { code: 'CNY', label: 'Chinese yuan' },
  { code: 'INR', label: 'Indian rupee' },
  { code: 'KRW', label: 'South Korean won' },
  { code: 'SGD', label: 'Singapore dollar' },
  { code: 'HKD', label: 'Hong Kong dollar' },
  { code: 'MXN', label: 'Mexican peso' },
  { code: 'BRL', label: 'Brazilian real' },
  { code: 'NOK', label: 'Norwegian krone' },
  { code: 'SEK', label: 'Swedish krona' },
  { code: 'DKK', label: 'Danish krone' },
  { code: 'PLN', label: 'Polish złoty' },
  { code: 'ZAR', label: 'South African rand' },
  { code: 'THB', label: 'Thai baht' },
  { code: 'PHP', label: 'Philippine peso' },
  { code: 'IDR', label: 'Indonesian rupiah' },
  { code: 'MYR', label: 'Malaysian ringgit' },
  { code: 'AED', label: 'UAE dirham' },
  { code: 'SAR', label: 'Saudi riyal' },
  { code: 'ILS', label: 'Israeli shekel' },
  { code: 'TRY', label: 'Turkish lira' },
  { code: 'CZK', label: 'Czech koruna' },
  { code: 'HUF', label: 'Hungarian forint' },
];
